### ISSUE TITLE
[Bug] TV Shows won't Open from Widgets

### ISSUE THREAD

**Issue by drinfernoo** [sualfred/skin.embuary#103]
It seems that I'm unable to interact with *any* TV show item on a widget, if that widget was filled from a plugin path. I've tested with library items, and it seems to work fine... but they don't even open with Embuary Info widgets.

Is there something that's happened recently to affect this? I'm almost certain it used to work 🤔 

Now, there is **no** action when a TV show item is selected. The path is never executed. I was able to press `I` to get a plot overview, which had a "Browse" button... but that didn't work either, appearing to simply run the plugin path using `RunPlugin(...)` or a similar method, rather than activating the appropriate window, which doesn't work with paths that should display a directory.

**Comment by sualfred** [comment]
Can you create me a small dummy addon to reproduce?

**Comment by drinfernoo** [comment]
No need. Create a widget with any add-on.

**Comment by drinfernoo** [comment]
I should say, this seems to be affecting *folder* items... since "Next Page" items don't work either.

**Comment by sualfred** [comment]
Tested:
-> Embuary Info -> Trendin Shows -> Info is opening without any problem
-> South Park addon with the season listing (folders) -> Opens correctly

Be sure you have configured the custom widget as "videos" as type.

**Comment by drinfernoo** [comment]
I've gone back to a fresh install for my test environment (18.6, at the moment) since I opened the issue... and they appear to be working now. I'm not sure what changed, but I'll close the issue unless I encounter it again.
