### ISSUE TITLE
addon required?

### ISSUE THREAD

**Issue by Mickroz** [sualfred/skin.embuary#107]
Is EmbyCon or Emby for Kodi required with this skin to work with Emby Server?
I can't seem to find if it is.

**Comment by Psychoses** [comment]
Both should work.

**Comment by Mickroz** [comment]
Ok, but one or the other is required to work with emby server?
There is no native connection build in this skin right?

**Comment by Psychoses** [comment]
yes, no native connection, u need install one of them.

**Comment by Mickroz** [comment]
Thank you for clarifying 👍
