### ISSUE TITLE
Kodi 19 (Matrix) Support

### ISSUE THREAD

**Issue by electrona** [sualfred/skin.embuary#112]
Can the skin be updated for Kodi 19 (Matrix)? This would also be needed to be ported to Python 3 if not already.

**Comment by Sada-Mio** [comment]
https://forum.kodi.tv/showthread.php?tid=320137&pid=3016545#pid3016545

**Comment by Aarontheissueguy** [comment]
This works very well. The only thing that seems to be buggy is the keyboard
