### ISSUE TITLE
Add better support for mouse

### ISSUE THREAD

**Issue by Ingvix** [sualfred/skin.embuary#12]
Tthe skin would be quite suitable for mouse usage if the upper left menu and return icon would be actually clickable and/or the left side menu would appear when cursor hits the side/stays a small moment at the side. Focus on widgets should also follow the cursor. Currently you cannot focus or click on items that are not fully visible, like the ones that are out of bounds of the screen.

Usability with keyboard and visual appearance of this skin is so far best I've used and seen so I really hope you continue developing this skin.

**Comment by sualfred** [comment]
No mouse and touch support.
