### ISSUE TITLE
execute executable from main menu

### ISSUE THREAD

**Issue by scrimpy** [sualfred/skin.embuary#13]
hi, is there an way to create links in the main menu with own executables? i'm using this build: https://forum.libreelec.tv/thread/302-le8-remix-generic-rpi-emulationstation-chrome-spotify-read-the-first-post-before/

in ordner to start emulatorstation, ... you a link with "XBMC.System.Exec(/usr/bin/emulationstation.sh)" for example. i cannot find this option in your skin.

**Comment by sualfred** [comment]
Haven't tested it but you can try two options:
- Create a dummy main menu item and then press the gear icon again. Now you will find a "custom item" option at the bottm of the list. 
- Edit your favourites.xml and use the new favourite as item for the main menu
