### ISSUE TITLE
When creating new profiles menu text is missing

### ISSUE THREAD

**Issue by milonedp** [sualfred/skin.embuary#18]
This skin is awesome!  It's so much better than everything else!  I use it with Super Favorites to create a page that has all my sources and Android video apps!!!

Where I'm having an issue is I'm trying to create profiles for my children and when I try to create a new one several areas have menu text missing.

It seems to work okay if I copy everything AND share media sources but as soon as you change that setting to separate the the menus go missing.

I need to be able to have different sources as I'm trying to use the parental settings and tie each profile in Kodi to a user in Emby.

Thanks

**Comment by sualfred** [comment]
That's a Kodi issue. Profiles are totally messed up. Sorry, but there's nothing that I can do on my side.
