### ISSUE TITLE
script.service.caretaker installed without consent

### ISSUE THREAD

**Issue by mgonzales71** [sualfred/skin.embuary#2]
Have a problem with:

`	<import addon="script.service.caretaker" version="0.0.5a"/>`

While I am not personally opposed to this particular script or it's purpose - the fact that your skin triggered it to be installed as a required supporting addon for the skin when this addon actually does nothing (0% - nada) for the skin or support of the skin's in any way.

Come on man - this is just bad form  😞 - maybe a dialog asking if the user would like to have it installed?

I just have a real bad dislike when things like this happen and **especially without notification / consent** etc no matter what they are for but specifically when they are not necessary or in support of what is already installed.

I found this to be troubling and it's upset me so I had to say something and I would respectfully like to ask you just maybe reconsider the way you install a non-skin related (supporting) addon like this especially and to not force install it without consent and then make it "required" on top of that so your can't uninstall or even disable it !!! 

Thanks,

Mario

PS - BTW I personally think you are a very talented Kodi skin dev and have enjoyed your work and contributions - much appreciated!

**Comment by sualfred** [comment]
One single word: self-protection.
I do not want to be associated with all the wizard builders and they already exist WITH pointing my name and my repo in descriptions.

Nothing is going to deleted, nothing is going to be tracked or similar. It just scans for installed blacklisted addons/repos and unloads my skin. If you have a clean system -> everything is fine.
