### ISSUE TITLE
Multi language incorrect in login form

### ISSUE THREAD

**Issue by kendling** [sualfred/skin.embuary#28]
![Screenshot_20190510_141952](https://user-images.githubusercontent.com/3919496/57506622-ef2e7580-732e-11e9-8b0d-5b3307eacdf9.png)

**Comment by sualfred** [comment]
Thx. Will take look into it

**Comment by sualfred** [comment]
Fixed with 
https://github.com/sualfred/skin.embuary/commit/2712c0f14b535b8c6e426eb954373d4aaed7771e
