### ISSUE TITLE
Support PlayOn

### ISSUE THREAD

**Issue by gabriellluz** [sualfred/skin.embuary#3]
Hi, I'm using your skin and it looks amazing. I've been using it as an Android launcher (through Kodi launcher). But when I use PlayOn kodi, I can't be able to choose a view that can actually show the description of the movie.

**Comment by sualfred** [comment]
Theres nothing I can do. The informations are shown in the info dialog and it's up to the addon devs to follow the info label guidelines and fill them correctly.
