### ISSUE TITLE
Python exception "coercing to Unicode: need string or buffer, NoneType found"

### ISSUE THREAD

**Issue by xam60** [sualfred/skin.embuary#30]
Hello,

Using Embuary with the addon Catch-up-TV-and-More https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore

I'm getting a Python error everytime Kodi starts. It tells "coercing to Unicode: need string or buffer, NoneType found".

It is related to Embuary addon as I don't get the error with Estuary one.

Please find the debug log :
https://paste.kodi.tv/igetoliwec.kodi

Thanks

**Comment by sualfred** [comment]
The exception is thrown by your used addon. You have to get in contact with the developer of this addon . There's nothing I can do.

**Comment by xam60** [comment]
Hello

The other team asks me what is the purpose of Unicode plugin installed with Embuary please 

Thanks

**Comment by sualfred** [comment]
I do not install any "unicode" plugin. And there is none. My helper script only uses the Kodi shipped modules. Unicode is a encoding type like UTF-8, ASCII, etc.
If you mean script.module.unidecode -> It's an dependency of script.skinshortcuts

I don't know your addon but It's an issue in the handling of a listitem as far as I can see.
