### ISSUE TITLE
Two seekbar in Plex for Kodi.

### ISSUE THREAD

**Issue by rosystain** [sualfred/skin.embuary#32]
Hello! 
I'm using Kodi DSPlayer with embuary and I love it so much.
It works great if using Emby as media source. But unfortunately, I am a user of PLEX.

Embuary still provides a great experience for videos which from smb but there is a little problem on the addon called 'Plex for Kodi'.  
'Plex for Kodi' have its own videoOSD. And if I change the playback progress, the the OSD of Embuary appears.  
<img width="1920" alt="Snipaste_2019-08-10_02-35-32" src="https://user-images.githubusercontent.com/27495128/63215619-f5b56000-c15b-11e9-8b5c-21dcbcc4eb83.png">

I found most of other skins do not have this problem but there is no other skin make me pleasure just like Embuary.
Any idea to solve it?

btw, Kodi DSPlayer is still under the version of Krypton. This is the only way for people using a HTPC to play HDR content with Kodi. 
Would you like to merge some features from the master branch to the Krypton's on one day?

**Comment by sualfred** [comment]
It's the a problem of Plex for Kodi. Addons should not overwrite general skin elements. I dunno why they made this crap decision. That's nothing I can or will fix, sorry.

I suggest you to switch to PKC to get a real native experience.

**Comment by rosystain** [comment]
Okay I will try PKC. Thank you
