### ISSUE TITLE
Add option for bigger font

### ISSUE THREAD

**Issue by ikus060** [sualfred/skin.embuary#50]
On 32" TV the font size defined by default in Embuary skin are too small for proper usage compare the default Estuary Skin.

Either the size of the font should be increased by default, or a new Font settings should be defined with bigger font to accommodate various user's need.

**Comment by ikus060** [comment]
From my understanding, I only need to provide a new font in Font.xml with different size.
If I do a PR, would it be accepted ?

**Comment by sualfred** [comment]
Wrong, that will crop everything here and there. As mentioned a couple of times over the last months: No support for bigger fonts. There is no place for it.
