### ISSUE TITLE
[FR] focusable scrollbars

### ISSUE THREAD

**Issue by farfromrefug** [sualfred/skin.embuary#6]
I have enabled scrollbars from the skin settings but i still can't focus them to scroll faster.
I suppose this is intended.
Could you add an option to make scrollbars usable, just like in estuary?

Thanks

**Comment by farfromrefug** [comment]
?? What does that mean? You implemented it? You don't want to do it?

**Comment by sualfred** [comment]
Not possible in all scenarios so it won't be added. The scrollbars are just indicators.
