### ISSUE TITLE
French translation available

### ISSUE THREAD

**Issue by capitaineflam25** [sualfred/skin.embuary#7]
Hi,

sorry to write here, it may not be the best place to do that.

Just to let you know that i've translated the strings to French on https://www.transifex.com/skinrefred/skinembuary/dashboard/

If you want to include it on a next released i will be happy to check if my translation are OK when in place.

Regards

**Comment by sualfred** [comment]
Thanks!
I'll add it. 

Note: 
Usually I always check Transifex before I push a new update. So you don't need to ping me in the future :) Again, thanks for your contribution.
