### ISSUE TITLE
Holiday theme widgets are empty

### ISSUE THREAD

**Issue by brainfork** [sualfred/skin.embuary#75]
Title explains the issue.  If these require manual set-up, I haven't seen any documentation explaining how to do that.

**Comment by sualfred** [comment]
No need to setup. It requires a local database (not EmbyCon). 
For Halloween it's based on genres and a whitelist:

`['ужас', 'užas', 'rædsel', 'horror', 'φρίκη', 'õudus', 'kauhu', 'horreur', 'užas',
                  'borzalom', 'hryllingi', 'ホラー', 'siaubas', 'verschrikking', 'skrekk', 'przerażenie',
                  'groază', 'фильм ужасов', 'hrôza', 'grozo', 'Skräck', 'korku', 'жах'
                  ]`

If none of these is available the widget won't be shown.

**Comment by brainfork** [comment]
> It requires a local database (not EmbyCon).
Thank you for clarifying that.  I'm using EmbyCon which explains why it's not working.

Is it possible to modify the whitelist, I have some TV episodes and some other Halloween movies that wouldn't fit under "Horror"

**Comment by sualfred** [comment]
Sure, let me know your suggestions and I'll add them if they won't return a "false positive".

**Comment by brainfork** [comment]
The example that comes to mind immediately would simply be "Halloween" but from the title rather than the genre:
- [_The Venture Bros._ - A Very Venture Halloween](https://www.thetvdb.com/series/the-venture-bros/episodes/4425286) 
- [Halloweentown](https://www.themoviedb.org/movie/27850-halloweentown?language=en-US)

Additionally, since the keywords are fetched from the genre and not the title, would something like [_The Simpsons_ - Treehouse of Horror](https://www.thetvdb.com/series/the-simpsons/episodes/55467) be excluded?

**Comment by sualfred** [comment]
I've added 'Halloween' as keyword and will also include movies and TV shows that have a keyword in the title. Plus if a plot contains "Halloween". 
Episodes won't be covered for this widget.
