### ISSUE TITLE
Request: Support openinfo

### ISSUE THREAD

**Issue by fugkco** [sualfred/skin.embuary#85]
Is it possible to support OpenInfo addon?

**Comment by sualfred** [comment]
No to banned addons

**Comment by fugkco** [comment]
Hi, maybe I'm misunderstanding.. but openinfo is a fork of the original script.extendedinfo which is in the official kodi repository. Why would openinfo be a banned addon? Regardless, thank you for considering either way.

**Comment by sualfred** [comment]
OpenInfo is made to support direct streaming and download links. That's why.
