### ISSUE TITLE
Speicals aren't being placed in the correct order

### ISSUE THREAD

**Issue by brainfork** [sualfred/skin.embuary#86]
Special episodes are being placed at the top of a season rather than between the episodes where they aired.

I'm using Emby & Embycon, the episodes show up as expected in the Emby server but not when viewed on Kodi.

**Comment by sualfred** [comment]
Kodi is collecting specials in a own special folder. Not by the airing date.

-> Specials -> Season 1 -> Season 2 -> etc.
