### ISSUE TITLE
Embuary Helper Error notification in Kodi DSPlayer (Krypton)

### ISSUE THREAD

**Issue by rosystain** [sualfred/skin.embuary#94]
It appears only at the first time when I play a video after Kodi launched.
Both of my two PCs which installed DSPlayer have this issue.

![screenshot003](https://user-images.githubusercontent.com/27495128/74827496-860d7100-5348-11ea-85c9-e467be346db8.png)

It tells me to check the log but I cannot find a separated one.
So I check the log of Kodi and find something about python error.
[kodi.log](https://github.com/sualfred/skin.embuary/files/4224650/kodi.log)

It seems nothing affected by this issue. But the error message makes me feel like that there is something I maked wrong.

**Comment by sualfred** [comment]
Krypton is EOL and supported has been dropped since a year, sorry.

**Comment by Chen-Runze** [comment]
@rosystain
I was also trapped in the error "Embuary Helper Error" with Kodi Leia Edition. Have you found the reason and the measure to solve it?
